### ISSUE TITLE
Rebind is broke when upgraded from v5 to v6

### ISSUE THREAD

**Issue by nitzcard** [remojansen/InversifyJS#1514] opened 2023-06-02 11:14 UTC
I tried upgrading from inversify 5 to 6, and now I see all the .rebind in my system do not work properly. 
The entity being rebinded, but when consumed thought another class later on, it still gets the first binding of the class. 

illustration:
```
di.bind('config').toConstantValue(7)
di.rebind('config').toConstantValue(8)
di.resolve('classThatUsingConfig') => config = 7
```

expected: config = 8 inside classThatUsingConfig

**Comment by weyert** [comment] 2023-12-05 00:50
Did you ever found a solution for this?

**Comment by Jameskmonger** [comment] 2023-12-17 14:15
Thanks for the report @nitzcard @weyert, I will investigate this and aim to resolve in the [`6.0.3` release](https://github.com/inversify/InversifyJS/milestone/18).

**Comment by weyert** [comment] 2023-12-17 16:34
@Jameskmonger Thank you, that would be great.

**Comment by notaphplover** [comment] 2024-11-12 20:50
Testing with the latest version (`inversify@6.1.3`), the behavior seems to be the expected one:

```ts
import 'reflect-metadata';

import { Container, inject, injectable } from 'inversify';

@injectable()
class Foo {
  readonly #property: number;

  constructor(@inject('config') param: number) {
    this.#property = param;
  }

  public get property(): number {
    return this.#property;
  }
}

@injectable()
class Bar {
  readonly #property: number;

  constructor(@inject('config') param: number) {
    this.#property = param;
  }

  public get property(): number {
    return this.#property;
  }
}

const container: Container = new Container();

container.bind('config').toConstantValue(7);
container.bind(Bar).toSelf().inSingletonScope();

const firstFoo = container.resolve(Foo);
const firstBar = container.resolve(Bar);

container.rebind('config').toConstantValue(8);

const configValue: number = container.get('config');
const secondFoo = container.resolve(Foo);
const secondBar = container.resolve(Bar);

console.log(`config value: ${configValue}`);
console.log(
  `(transient) object binded value before rebind ${firstFoo.property}`,
);
console.log(
  `(transient) object binded value after rebind ${secondFoo.property}`,
);
console.log(
  `(sinfleton) object binded value before rebind ${firstBar.property}`,
);
console.log(
  `(sinfleton) object binded value after rebind ${secondBar.property}`,
);
```

Which prints:

```
config value: 8
(transient) object binded value before rebind 7
(transient) object binded value after rebind 8
(sinfleton) object binded value before rebind 7
(sinfleton) object binded value after rebind 7
```

- Config value is 8 ✅ .
- `Foo` is instantiated with a bound `7` config before the rebind operation ✅.
- `Foo` is instantiated with a bound `8` config after the rebind operation ✅.
- `Bar` is instantiated with a bound `7` config before the rebind operation ✅.
- `Bar` is instantiated with a bound `7` config after the rebind operation because it's already cached ✅. Unbind does not trigger the cache clear of dependent services.

I'll close the issue now. Feel free to comment if you'd like to discuss this and I'll reopen the issue if the current behavior of a minimum reproduction code you provide is not the expected one 😃.

**Closed as completed by notaphplover** 2024-11-12 20:50 UTC
