### ISSUE TITLE
"inversify-express-utils" has no exported member named 'withMiddleware'.

### ISSUE THREAD

**Issue by bombitmanbomb** [remojansen/InversifyJS#1583] opened 2024-09-18 02:05 UTC
## Expected Behavior
import `withMiddleware` to create decorator middleware, [as described in the documentation](https://github.com/inversify/inversify-express-utils?tab=readme-ov-file#middleware-decorators).

## Current Behavior
```
"inversify-express-utils" has no exported member named 'withMiddleware'.
```

Currently using the latest available release (`v6.4.6`)

**Comment by notaphplover** [comment] 2024-10-22 10:44
Closing as duplicate of #1577. It is a bug!

Please follow the above issue to check the resolution status

**Closed as completed** 2024-10-22 10:44 UTC
Labels: bug, duplicate, express-utils
