### ISSUE TITLE
Injecting an object with a .then property which is not a promise resolves to undefined

### ISSUE THREAD

**Issue by brahms116** [remojansen/InversifyJS#1570] opened 2024-05-30 05:30 UTC
When you inject an object with a property of `.then` but its not a promise, it resolves to undefined. This is because when resolving it believes that its a `promise` when its not

## Expected Behavior

This should pass...

```
import { expect } from "chai";
import { Container, inject, injectable } from "../../src/inversify";

describe("Issue", () => {
  it("It should not return injected value as undefined if the value contains a .then property but it is not a promise", () => {
    const container = new Container();

    interface Injected {
      myProperty: string;
      then: () => number;
    }

    @injectable()
    class ResolveMe {
      constructor(@inject("Injected") public injected: Injected) {}
    }

    container.bind("Injected").toConstantValue({
      myProperty: "myNewProperty",
      then: () => 1
    });

    const me = container.resolve(ResolveMe);
    expect(me.injected.myProperty).to.eql("myNewProperty");
  });
});
```

## Current Behavior

`injected` resolves to undefined

## Possible Solution

I have linked a PR for a possible approach https://github.com/inversify/InversifyJS/pull/1571

**Comment by notaphplover** [comment] 2024-10-24 18:39
Hey @brahms116, I had a look at your issue.

Inversify relies on the Promises/A+ standard and tries to apply their resolution algorithm when it detects a [thenable](https://promisesaplus.com/#terminology).

According to [the standard resolution procedure](https://promisesaplus.com/#point-45), `"Injected"` must be resolved to the value `1`.

Consider this passing test:

```ts
import { expect } from "chai";
import { Container, inject, injectable } from "../../src/inversify";

describe("Issue 1570", () => {
  it("It should not return injected value as undefined if the value contains a .then property but it is not a promise", () => {
    const container = new Container();

    interface Injected {
      myProperty: string;
      then: () => number;
    }

    @injectable()
    class ResolveMe {
      constructor(@inject("Injected") public injected: Injected) {}
    }

    container.bind("Injected").toConstantValue({
      myProperty: "myNewProperty",
      then: () => 1,
    });

    const me = container.resolve(ResolveMe);
    expect(me.injected).to.eql(1);
  });
});

```

This is the expected behavior when working with `thenables`, we cannot rely on the `Promise` class because it's not the only possible expected `Promise`. Any class implementing the Promises/A+ spec is a valid promise as well, and I would suggest you not to rely on `instance of Promise` to detect a `Promise` for such a reason.

I'll close this issue now. If you wish to continue the discussion, feel free to reply me in this issue and I'll reopen it asap.

**Closed as completed by notaphplover** 2024-10-24 18:39 UTC
