### ISSUE TITLE
[inversify] index signature parameter type must be either 'string' or 'number'

### ISSUE THREAD

**Issue by xenoterracide** [remojansen/InversifyJS#1459] opened 2022-05-17 20:05 UTC
```
node_modules/inversify/lib/interfaces/interfaces.d.ts:275:10 - error TS1023: An index signature parameter type must be either 'string' or 'number'.

275         [propertyNameOrArgumentIndex: string | symbol]: Metadata[];
```

```
❯ uname -a && node --version && npm explain inversify typescript
Darwin 5c52309d33e3 20.6.0 Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:41 PST 2022; root:xnu-7195.141.26~1/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin
v16.14.2
inversify@6.0.1
node_modules/inversify
  inversify@"^6.0.1" from inversify-express-utils@6.4.3
  node_modules/inversify-express-utils
    inversify-express-utils@"^6.4.3" from back-end@0.0.0
    back-end
      back-end@0.0.0
      node_modules/back-end
        workspace back-end from the root project
  inversify@"^6.0.1" from back-end@0.0.0
  back-end
    back-end@0.0.0
    node_modules/back-end
      workspace back-end from the root project

typescript@4.3.5 dev
node_modules/typescript
```

**Comment by PodaruDragos** [comment] 2022-05-17 20:24
yeah and that's right. please upgrade typescript to at least 4.4

**Comment by timo-kang** [comment] 2022-07-19 02:44
same issue on `typescript v4.7.4` and `tsc --version` is `4.2.3`

**Comment by timo-kang** [comment] 2022-07-19 02:47
oh, I upgraded tsc with 4.7.4 by `npm i typescript@4.7.4 -g`, and it worked! thanks

**Comment by danielherrerasanchez92** [comment] 2022-07-22 16:49
Same issue here. Upgrading to **typescript@4.7.4** worked like a charm !

**Comment by notaphplover** [comment] 2024-11-21 17:25
Closing as the issue is related to `tsc` version.

**Closed as completed by notaphplover** 2024-11-21 17:25 UTC
