### ISSUE TITLE
Option `skipBaseClassChecks` has no effect when inheritance is being used

### ISSUE THREAD

**Issue by lucianlature** [remojansen/InversifyJS#1558] opened 2024-02-15 16:51 UTC
Please check [this stackblitz project](https://stackblitz.com/edit/typescript-inversify-neeqgd?file=index.ts) to see the issue.

Basically, although `skipBaseClassChecks` is set to `true`, the checks are still being performed.

Any idea why this is happening?....Something wrong in my setup?

## Expected Behavior

When `skipBaseClassChecks` is set to `true`,  the container will disable all checking of base classes.

## Current Behavior

Even if `skipBaseClassChecks` is set to `true`,  the container will keep all checking of base classes,

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

Check the link above for the stackblitz project that is showing the faulty behaviour.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

# Stack trace

**Comment by notaphplover** [comment] 2024-11-14 14:00
Hey @lucianlature, having a look at the  [docs](https://github.com/inversify/InversifyJS/blob/master/wiki/inheritance.md):

>### WORKAROUND E) Skip Base class checks
>
>Setting the `skipBaseClassChecks` option to `true` for the container will disable all checking of base classes. This means it will be completely up to the developer to ensure that the `super()` constructor is called with the correct arguments and at the correct time.

The repro you passes me fails resolve `Baltag` because it has a parameter with no `@inject` annotation regardless of its base type implementation.

This is the expected behavior. To tell inversify you want to manage that param yourself, rely on `@unmanaged`:

```ts
@injectable()
class Baltag extends Weapon {
  public hit() {
    return 'auleu!';
  }

  constructor(@unmanaged() data: any) {
    super(data);

    console.log('baltag');
  }
}
```

I'm closing this issue now. Feel free to continue discussing in this thread if you think I'm missing something :smiley:.

**Closed as completed by notaphplover** 2024-11-14 14:00 UTC
